import Head from "next/head";
import styles from '@styles/modules/home.module.scss';
import { MainBackground } from "./sections/background";
import { MainForm } from "./sections/content";

export default function StacksCalculator() {
  return (
    <>
      <Head>
        <title>League Stacks Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.mainContainer}>
        <MainBackground/>
      </main>
    </>
  );
}
