import Head from "next/head";

export default function StacksCalculator() {
  return (
    <>
      <Head>
        <title>League Stacks Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      </div>
    </>
  );
}
